### ISSUE TITLE
Add redis session middleware & Redis fsm storage

### ISSUE THREAD

**Issue by DiorDS** [dsodx/30-bot#10]

**Comment by dsodx** [comment]
Кто бы мог подумать )

**Comment by DiorDS** [comment]
Мне кэш нужен просто

**Comment by DiorDS** [comment]
а раз уже есть, редис то и добавим

**Comment by dsodx** [comment]
а не знаешь, может мой ttl кэш тоже можно в редис перенести?

**Comment by DiorDS** [comment]
> а не знаешь, может мой ttl кэш тоже можно в редис перенести?

ага
